### PR TITLE
fix broken link

### PR DESCRIPTION
**Pull request by chenpengdev**
fix broken link

### CODE REVIEW

**Comment by quinton-hoole** [comment]
/lgtm

@irfanurrehman Are there any other links that broke as a result of the repo move?

**Comment by irfanurrehman** [comment]
> @irfanurrehman Are there any other links that broke as a result of the repo move?

@quinton-hoole I did give a pass at most of the documentation (with more focus on federation docs published at `https://kubernetes.io/`). In federation repo, we did find replace all `k8s.io/kubernetes/federation` to `k8s.io/federation`, this seems missed because of that. Meanwhile the api reference docs are actually published at `kubernetes.io` docs authoritatively, for example `https://kubernetes.io/docs/reference/generated/federation/federation/v1beta1/operations/`.

**Pull request merged**
