### PR TITLE
ISS-35637: Mock out the internet

### PR DESCRIPTION
**Pull request by nikox94**
This abstracts away the internet through an interface and tests the hostname resolving for AWS LBs

### CODE REVIEW

**Comment by nikox94** [comment]
@quinton-hoole Please bear in mind that I have not written Go for some time and, for example, I am not so sure if I have correctly done exported vs. nonexported structs and interfaces. I will have a second look myself soon as well.

**Comment by quinton-hoole** [comment]
/lgtm

Thanks @nikox94 !

**Pull request merged**
