### PR TITLE
ISSUE-185: Init e2e README.md

### PR DESCRIPTION
**Pull request by nikox94**
https://github.com/kubernetes/federation/issues/185

### CODE REVIEW

**Comment by irfanurrehman** [comment]
@nikox94, Thanks for doing this. The general idea looks ok. How about updating some helper scripts (something like federation_e2e_local.sh), which can do stuff rather then user running all the steps individually. You can take inspiration from https://github.com/kubernetes/community/blob/master/contributors/devel/e2e-tests.md#federation-e2e-tests (the outdated documentation) and https://github.com/kubernetes/federation/tree/master/deploy/cluster (which are also sort of outdated).

**Comment by nikox94** [comment]
Tests ran on a single started node with no joined machines:
```
_output/dockerized/bin/linux/amd64/e2e.test --kubeconfig ~/.kube/config --federated-kube-context myfed
```

https://gist.github.com/nikox94/a96a7672eec93066848749a4c2d70bf0

**Comment by nikox94** [comment]
Another run regarding this:
https://gist.github.com/nikox94/4f3ad4d203e3d390eb414e2bd9e2d78b

**Comment by jdumars** [comment]
Hi, please get your CLA signed, and we will ok this for testing. Thanks!

**Comment by nikox94** [comment]
Thank you!

На 3.03.2018 г. 4:01 "Jaice Singer DuMars" <notifications@github.com>
написа:

Hi, please get your CLA signed, and we will ok this for testing. Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/federation/pull/186#issuecomment-369983344>,
or mute the thread

**Comment by nikox94** [comment]
Hey!

I am sorry, but I think I already did sign it... will check again.

Apologies for the delay, moved countries recently. 

Looking forward to getting this finished.

**Comment by nikox94** [comment]
OK so it seems my commits are missing my email, which is causing the issue with the CLA. fixing..

**Comment by shashidharatd** [comment]
Thanks @nikox94 for doing this.
/lgtm

**Comment by nikox94** [comment]
OK @shashidharatd , please ping me when it's done

**Comment by idealhack** [comment]
This seems to be nice to have.

/reopen

**Pull request closed without merging**
