### PR TITLE
Convert the Job controller to a sync controller

### PR DESCRIPTION
**Pull request by font**

### CODE REVIEW

**Comment by irfanurrehman** [comment]
@font how did u run the e2e for this change? It seems to fail always for jobs. Can you please have a look.

**Comment by font** [comment]
@irfanurrehman I was trying to use the prow job to perform e2e testing as there were some issues running it locally. Please hold off reviewing until I get it straightened out.

**Comment by font** [comment]
@irfanurrehman Are these instructions for running federation e2e tests accurate? https://github.com/kubernetes/community/blob/master/contributors/devel/e2e-tests.md#federation-e2e-tests

**Comment by irfanurrehman** [comment]
@font No (this needs to be updated or removed), but the general idea remains same.
There is a gap in current k8s docs and it is a little more tricky to actually achieve this in the local environment.
@nikox94 volunteered to do this and raised [this PR](https://github.com/kubernetes/federation/pull/186). Can u please try it out and validate the same too.
U can try out with some other cloud provider cluster also (if you want to), in place of minikube, but still follow the steps in @nikox94's PR.

**Comment by nikox94** [comment]
Hey @font ! I am indeed working on this, however my PR is currently a disorganized dump of instructions. It's linked to issue #185 , you can find it there.

Please give me a day or two to straighten it out as I am still working on it, or, you are free to try the instruction dump and give me your feedback.

Regards! :) Thanks for coding free! :)

**Comment by irfanurrehman** [comment]
@font, were you able to run the e2e locally?

**Comment by font** [comment]
@irfanurrehman Yes, after #184 merged I was able to test e2e locally with minikube. I have not looked at the instructions in the PR that addresses #185.

**Comment by font** [comment]
@irfanurrehman @jianhuiz I am not able to successfully run e2e `job` tests locally with the changes in this PR nor with master@HEAD. I keep getting:

```
STEP: Creating federation job "federation-job" in namespace "e2e-tests-federation-job-964z7"                                                                                                                       
Jan 20 21:45:24.220: INFO: Unexpected error occurred: the server could not find the requested resource (post jobs.batch)
```
That error happens when attempting to run any of the enabled job tests:

```
[k8s.io] Federation jobs [Feature:Federation] Federated Job should be deleted from underlying clusters when OrphanDependents is false
[k8s.io] Federation jobs [Feature:Federation] Federated Job should create and update matching jobs in underlying clusters
[k8s.io] Federation jobs [Feature:Federation] Federated Job should not be deleted from underlying clusters when OrphanDependents is nil
[k8s.io] Federation jobs [Feature:Federation] Federated Job should not be deleted from underlying clusters when OrphanDependents is true
```
The federated API server does not seem to recognize the `batch/v1` `Job` type as even trying to manually create a test job through the FCP fails with:

```
→ kubectl --context echelon create -f pi-job.yaml 
error: error validating "pi-job.yaml": error validating data: unknown object type schema.GroupVersionKind{Group:"batch", Version:"v1", Kind:"Job"}; if you choose to ignore these errors, turn validation off with --validate=false
→ kubectl --context echelon create -f pi-job.yaml --validate=false
error: unable to recognize "pi-job.yaml": no matches for batch/, Kind=Job
```

Creating the same test job when talking to the K8s API server succeeds of course.

On the other hand, I'm able to successfully run the following tests either with the changes from this PR or with master@HEAD:

```
[k8s.io] Federated types [Feature:Federation][Experimental] Federated "configmap" resources should be created, read, updated and deleted successfully
[k8s.io] Federated types [Feature:Federation][Experimental] Federated "daemonset" resources should be created, read, updated and deleted successfully
[k8s.io] Federated types [Feature:Federation][Experimental] Federated "deployment" resources should be created, read, updated and deleted successfully
[k8s.io] Federated types [Feature:Federation][Experimental] Federated "horizontalpodautoscaler" resources should be created, read, updated and deleted successfully
[k8s.io] Federated types [Feature:Federation][Experimental] Federated "namespace" resources should be created, read, updated and deleted successfully
[k8s.io] Federated types [Feature:Federation][Experimental] Federated "replicaset" resources should be created, read, updated and deleted successfully
[k8s.io] Federated types [Feature:Federation][Experimental] Federated "secret" resources should be created, read, updated and deleted successfully
```
I have not tried any other tests.

It seems like the `Job` API is not enabled, but I'm not sure why the `pull-federation-e2e-gce` test seems to run successfully on other PRs. Do you know what could be causing this? I haven't had time to look further into this as it's not currently high on my priorities.

**Comment by irfanurrehman** [comment]
@font, I guess you are running apiserver with its default params. The job API is not enabled by default. You can use `--apiserver-arg-overrides="--runtime-config=api/all=true"` as an argument to kubefed while deploying the apiserver. In the e2e and integration test fixtures the apiserver is run with all APIs enabled.

**Comment by font** [comment]
@irfanurrehman I see that in the code now, thanks! This should be documented as one is expecting jobs to be fully enabled just like the rest of the APIs. https://kubernetes.io/docs/tasks/administer-federation/job/ does not mention this.

**Comment by irfanurrehman** [comment]
@font, thanks for pointing this out. I have raised #198 for this.

**Pull request closed without merging**
