### PR TITLE
Migrate from glide to golang/dep and also bump vendor

### PR DESCRIPTION
**Pull request by shashidharatd**
This PR does following things.
- Migrate from glide to golang/dep as dependency management tool
- Bump the k8s dependency to v1.10.0-alpha.3 and adapt the usage in federation
- Refactor the test codes to not use `k8s.io/kubernetes/test/e2e/framework` (as it is one huge package and lot many unnecessary stuff gets imported. So pulled in only necessary funcs into a reusable package within federation).
- Few other miscellaneous stuff.

/cc @kubernetes/sig-multicluster-pr-reviews 
/assign @irfanurrehman 

p.s: Even though the PR is huge, most of it is either generated code or vendored code. So request to review commit by commit which is much easier.

### CODE REVIEW

**Comment by shashidharatd** [comment]
To get `dep` working with federation repo, we mostly followed the notes from @justinsb [here](https://github.com/kubernetes/kubernetes/issues/44873#issuecomment-362989050) and couple more tweaks. So here are the details:
- Used `required` block to declare dependencies that are used by build and test scripts but not imported directly by code in the repo.
- Reused the script which compares version in `Godeps.json` of k/k with the dependencies resolved by `dep`, output as below which helps in fixing the versions in `Gopkg.toml` and be compatible with k/k.
```
root@xxx-laptop:~/gopath/src/k8s.io/federation# ./hack/dep.py 
# update needed: github.com/chai2010/gettext-go c6fed771bfd517099caf0f7a961671fa8ed08723 vs bf70f2a70fb1b1f36d90d671a72795984eab0fcb
[[override]]
  name = "github.com/chai2010/gettext-go"
  revision = "c6fed771bfd517099caf0f7a961671fa8ed08723"
# Missing dep github.com/petar/GoLLRB, currently at version branch master
# Missing dep k8s.io/api, currently at version kubernetes-1.10.0-alpha.3
# Missing dep k8s.io/apiextensions-apiserver, currently at version kubernetes-1.10.0-alpha.3
# Missing dep k8s.io/code-generator, currently at version kubernetes-1.10.0-alpha.3
# Missing dep k8s.io/client-go, currently at version kubernetes-1.10.0-alpha.3
# Missing dep google.golang.org/appengine, currently at version branch master
# Missing dep k8s.io/apimachinery, currently at version kubernetes-1.10.0-alpha.3
# Missing dep github.com/coredns/coredns, currently at version v1.0.5
# Missing dep k8s.io/apiserver, currently at version kubernetes-1.10.0-alpha.3
# Missing dep k8s.io/metrics, currently at version kubernetes-1.10.0-alpha.3
# Missing dep k8s.io/kubernetes, currently at version v1.10.0-alpha.3
```
Note: Some of these packages in `k8s.io/` does not have a record in `Godeps.json` in k/k. It would help to publicise these repo versions in releases. But anyway they are all tagged with release version.
- The version for `github.com/chai2010/gettext-go` in Godeps.json breaks `dep ensure`. So using the same version as used in `kops` fixed the issue.
- For bazel, as with kops, we had to delete all the `BUILD` files from vendor directory and regenerate them. It worked except for 2 issues which had to be manually resolved.
  - The version `3.2.13` for `github.com/coreos/etcd` which we used, has symlinks in [cmd](https://github.com/coreos/etcd/tree/v3.2.13/cmd), which does not work with bazel. So had to be removed manually.
  - boilerplates are required for code auto-generation but does not have go code, [here](https://github.com/kubernetes/kubernetes/tree/master/hack/boilerplate). So vendoring them was not possible automatically with dep. probably once this [issue](https://github.com/golang/dep/issues/1306) is addressed, we should be able to use it properly.

/cc @mattfarina, @marun. request to PTAL. esp https://github.com/kubernetes/federation/pull/237/commits/bffc47bb8cf72772009f483aab8e156d6bc625d2

**Comment by irfanurrehman** [comment]
@shashidharatd I was having a look at different commits. One thing that strikes me as a future problem is copying and maintaining the e2e framework into federation repo. I agree that is reduces the overall vendor size, but I would recommend to let the folks responsible for maintaining the k8s e2e fw, still maintain it. We can try to pitch our case for having that portion of code out of k/k for it to be easier to be used by other projects.

**Comment by shashidharatd** [comment]
@irfanurrehman, I agree and concur with your opinion. But importing the `k8s.io/kubernetes/test/e2e/framework` brings in lot of unwanted packages and also need to import the generated code. Our usage of this framework is little and does not change much in the longer run. It makes sense for us to maintain it ourselves. Also going forward we shall refactor the framework to only things which we need.

**Comment by irfanurrehman** [comment]
Agree. Thanks for doing this @shashidharatd.
/lgtm

**Comment by shashidharatd** [comment]
Thanks @irfanurrehman

**Pull request merged**
