### PR TITLE
Fed move out cleanup - part 1

### PR DESCRIPTION
**Pull request by irfanurrehman**
This pull request is not yet complete.
The PR is to get comprehensive test signals, rather then running everything locally.

cc @marun @shashidharatd 
/assign

### CODE REVIEW

**Comment by irfanurrehman** [comment]
@marun @shashidharatd can u please have a look at this one; This should be easy to approve as a first step on cleanup, in which I have removed the stuff which I know is surely unused. 
Further steps might be as below:
 - When the e2e moves to kubernetes-anywhere, we can simply do away with the cluster and deploy folders (ideally federation_up/down.sh also should not be needed, and kubefed used directly instead).
- Fixate our build mechanism to bazel and do away with makefiles and all supporting build scripts.
- Cleanup hack and build folders of remaining unused code.
- Possible reorganisation of any needed code (for example hack/verify stuff)

**Comment by shashidharatd** [comment]
@irfanurrehman, This looks good to me. But would wait until all CI issues are fixed and are green.

**Comment by irfanurrehman** [comment]
This PR now seems to be complete and the steps I mentioned in the previous message can be taken as separate PRs.
cc @marun @shashidharatd

**Pull request merged**
