### PR TITLE
Updates to make federation e2e CI jobs work 

### PR DESCRIPTION
**Pull request by irfanurrehman**
Updates to ensure e2e jobs can run ok on this repo.
cc @shashidharatd @marun 
cc @kubernetes/sig-multicluster-pr-reviews

### CODE REVIEW

**Comment by shashidharatd** [comment]
This pr looks good to me now. pull-federation-e2e-gce should succeed once the test-infra fixes are  merged.
/lgtm

**Comment by irfanurrehman** [comment]
@marun @shashidharatd any thoughts on merging this manually vs waiting for verify job to be green ?

**Comment by irfanurrehman** [comment]
> @marun @shashidharatd any thoughts on merging this manually vs waiting for verify job to be green ?

@marun @shashidharatd thoughts ?
meanwhile, I have pushed the kubefed fix (which otherwise would have gone into another PR) in this one.  Please additionally check [this](https://github.com/kubernetes/federation/pull/114/commits/f3740fa14baa23cde05e7de348d08e649c56a75e) once

**Comment by irfanurrehman** [comment]
merging this manually as verify will not succeed on this one.

**Pull request merged**
