### PR TITLE
Remove duplicated words

### PR DESCRIPTION
**Pull request by mooncak**
Remove duplicated words in below files to make it more clearly:
1. pkg/dnsprovider/providers/aws/route53/interface.go
2. pkg/federation-controller/cluster/clustercontroller_test.go
3. test/k8s/e2e/framework/framework.go

### CODE REVIEW

**Comment by mooncak** [comment]
@madhusudancs @quinton-hoole @marun  could you pls help review and approve? tks

**Comment by quinton-hoole-2** [comment]
The above error is due to the fact that I changed github user name, and the relevant owners files have not yet been updated.  I'll try to get all that resolved, but in the mean time perhaps @shashidharatd or @irfanurrehman can type /approve.

**Comment by shashidharatd** [comment]
/approve
@mooncak, development is almost seized in this repo. request to give a try in https://github.com/kubernetes-sigs/federation-v2

**Comment by mooncak** [comment]
> /approve
> @mooncak, development is almost seized in this repo. request to give a try in https://github.com/kubernetes-sigs/federation-v2

ok

**Comment by mooncak** [comment]
@quinton-hoole-2 @shashidharatd    Could you also add /ok-to-test label? thanks.

**Comment by mooncak** [comment]
@madhusudancs @quinton-hoole @quinton-hoole-2  Can you also add /ok-to-test label? thanks.

**Comment by quinton-hoole-2** [comment]
@mooncak I don't think anyone's interested enough in such a small PR to fix minor code comments in deprecated code to get this merged.  Please stop pinging this PR.   I would suggest that you run an automated grammar checker across all the kubernetes/* code, and submit the smallest number of PR's possible to address all of those issues.  Please close this PR.

**Pull request closed without merging**
